# ETAPA 1: Construcción del estático
FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# ETAPA 2: Servidor Web ligero
FROM nginx:alpine
# Copiamos solo los archivos de la carpeta build/dist de Svelte
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
