apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: clone-run-
spec:
  pipelineRef:
    name: source-clone-pipeline
  workspaces:
    - name: shared-workspace
      emptyDir: {}
  params:
    - name: repo-url
      value: "https://github.com/dguerrero11/clasedevops.git"
