apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    alerting:
      alertmanagers:
        - static_configs:
            - targets:
              - alertmanager-service:9093
    rule_files:
      - '/etc/prometheus/rules/*.yml'

    scrape_configs:
      # Regla 1: Monitorear el propio servidor de Prometheus
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      # Regla 2: Auto-descubrimiento de Pods anotados en el clúster (Tu Tienda NoNameStore)
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
        - role: pod
          namespaces:
            names:
            - default
            - monitoring
            - staging
      # NUEVA REGLA 3: Leer el estado del clúster (Fundamental para alertas de pods)
      - job_name: 'kube-state-metrics'
        static_configs:
          - targets: ['kube-state-metrics.kube-system.svc.cluster.local:8080']
