apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-nonamestore-pipeline
spec:
  workspaces:
    - name: shared-workspace
  params:
    - name: repo-url
      type: string
      description: https://github.com/Gus0519/nonamestore
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: $(params.repo-url)
        - name: deleteExisting
          value: "true"
