apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nonamestore-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Gus0519/nonamestore.git' # Tu repo
    targetRevision: main
    path: k8s/prod # <--- La nueva carpeta que Argo vigilará
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: prod # <--- El nuevo namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true # Esto hace que Argo cree el namespace "prod" por ti
