apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv-prod
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  nfs:
    path: /mnt/lab_storage/DevOps/proyecto/nfs_share_prod
    server: 192.168.122.1  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc
  namespace: prod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: manual
  volumeName: mariadb-pv-prod
